### PR TITLE
Use protocol relative URL for OSM tiles

### PR DESCRIPTION
**Pull request by mprins**
OpenStreetMap have enabled SSL on their services and website. Using protocol relative URLs for the tiles takes advantage of this work out of the box.

see: 
- OSM blog: http://blog.openstreetmap.org/2014/02/11/osm-enhances-user-privacy/
- specification: [IETF RFC 3986](http://www.ietf.org/rfc/rfc3986.txt) section 4.2

### CODE REVIEW

**Comment by harry-wood** [comment]
This fix didn't make it into 2.13.1 hey? How do the releases work around here? Is there a development release of OpenLayers 2 any more?

**Comment by bartvde** [comment]
OpenLayers 2 is not maintained anymore, so don't expect new releases from it

**Comment by harry-wood** [comment]
Indeed. But I was just confused because unless I'm mistaken the last release that *did* happen (and the last available hosted version on cloudflare), version 2.13.1,  was August 2014, but somehow didn't seem to include this fix, even though it was merged Feb 2014. That's a bummer.

I see there's still some commits to this repo. But no releases hey? I was hoping there might be hosted "nightly" development builds or something, but ([looking back when the "development" site was still working](https://web.archive.org/web/20150205083932/https://trac.osgeo.org/openlayers/wiki/HowToDownload)) it looks like it was only ever the fixed releases up to 2.13.1

**Comment by bartvde** [comment]
2.13.1 was probably a patch release on top of 2.13, so it did not include all other fixes from master, just regressions

It should be easy enough to build your own?

**Pull request merged**
