### PR TITLE
Rework Google layer

### PR DESCRIPTION
**Pull request by ahocevar**
We should rework the Google layer to avoid the dom shuffle.  See http://code.google.com/p/google-maps-utility-library-v3/source/browse/trunk/googleearth/src/googleearth.js#819 for an example of adding an event blocking element as a map pane.

### CODE REVIEW

**Comment by joaorodr84** [comment]
Hi @ahocevar 
The opacity is still not working in the Google layer.
http://codepen.io/joaorodr84/pen/PqaEww
I understand that the OpenLayers map is now INSIDE the GMaps map, so I assume it is very diffisult to re-implement the setOpacity for the Google layer.
I was wondering if any workarounds have been found since your last post about this issue, or if this issue is being worked on.
Thanks a lot.

**Comment by ahocevar** [comment]
To my knowledge, no one is working on this.

**Comment by joaorodr84** [comment]
Ok. Thanks. Do you know if there is a solution to this?

**Comment by ahocevar** [comment]
You can try with css.

**Comment by joaorodr84** [comment]
I tried, but with CSS, the opacity applies to the whole map. The map is inside the GMap container, so the CSS applied to the Google layer, affects the whole OpenLayers map. And that is not what I want. I want to change opacity only in the Google layer.

**Pull request merged**
